
(function(global){var Position={CENTER:"center",TOP_LEFT:"top_left",TOP_CENTER:"top_center",TOP_RIGHT:"top_right",MIDDLE_LEFT:"middle_left",MIDDLE_CENTER:"center",MIDDLE_RIGHT:"middle_right",BOTTOM_LEFT:"bottom_left",BOTTOM_CENTER:"bottom_center",BOTTOM_RIGHT:"bottom_right"};var Transform=function(svgElement,centerPoint){this.sourceSVGElement=svgElement;this.prefix=(typeof svgElement.prefix==="string")?svgElement.prefix+":":"";this.init(centerPoint);};Transform.prototype.init=function(centerPoint){this.wrapper=document.createElementNS("http://www.w3.org/2000/svg",this.prefix+"g");this.transformWrapper=document.createElementNS("http://www.w3.org/2000/svg",this.prefix+"g");this.wrapper.setAttribute("class","Transform");this.transformWrapper.setAttribute("class","SVGTransformWrapper");this.sourceSVGElement.parentNode.replaceChild(this.wrapper,this.sourceSVGElement);this.wrapper.appendChild(this.transformWrapper);this.transformWrapper.appendChild(this.sourceSVGElement);this.svgElement=this.wrapper;this.origOffset={x:this.transformWrapper.getBBox().x,y:this.transformWrapper.getBBox().y};this.origWidth=this.transformWrapper.getBBox().width;this.origHeight=this.transformWrapper.getBBox().height;this._transform={x:0,y:0,scaleX:1,scaleY:1,rotate:0};this._setCenterPoint(centerPoint);};Transform.prototype._setCenterPoint=function(centerPoint){if(!this._x||!this._y){switch(centerPoint){case Position.CENTER:centerPoint=Position.CENTER;break;case Position.TOP_LEFT:centerPoint=Position.TOP_LEFT;break;case Position.TOP_CENTER:centerPoint=Position.TOP_CENTER;break;case Position.TOP_RIGHT:centerPoint=Position.TOP_RIGHT;break;case Position.MIDDLE_LEFT:centerPoint=Position.MIDDLE_LEFT;break;case Position.MIDDLE_RIGHT:centerPoint=Position.MIDDLE_RIGHT;break;case Position.BOTTOM_LEFT:centerPoint=Position.BOTTOM_LEFT;break;case Position.BOTTOM_CENTER:centerPoint=Position.BOTTOM_CENTER;break;case Position.BOTTOM_RIGHT:centerPoint=Position.BOTTOM_RIGHT;break;default:centerPoint=Position.CENTER;break;}
this.centerPoint=centerPoint;var x=this.origOffset.x+this.getCX();var y=this.origOffset.y+this.getCY();this.setX(x);this.setY(y);}};Transform.prototype.setTransform=function(transform){if(typeof transform=="undefined"){return;}
var x=(typeof transform.x=="number")?transform.x:this._transform.x;var y=(typeof transform.y=="number")?transform.y:this._transform.y;var scaleX=(typeof transform.scaleX=="number")?transform.scaleX:this._transform.scaleX;var scaleY=(typeof transform.scaleY=="number")?transform.scaleY:this._transform.scaleY;var rotate=(typeof transform.rotate=="number")?transform.rotate:this._transform.rotate;var cx=-this.getCX();var cy=-this.getCY();var offsetX=-this.origOffset.x;var offsetY=-this.origOffset.y;this._transform.x=x;this._transform.y=y;this._transform.scaleX=scaleX;this._transform.scaleY=scaleY;this._transform.rotate=rotate;var _translate="translate("+x+" "+y+") ";var _rotate="rotate("+rotate+") ";var _scale="scale("+scaleX+" "+scaleY+") ";var _centerTranslate="translate("+cx+" "+cy+") ";var _offsetTranslate="translate("+offsetX+" "+offsetY+") ";this.transformWrapper.setAttribute("transform",_translate+_rotate+_scale+_centerTranslate+_offsetTranslate);};Transform.prototype.getWidth=function(){return this.wrapper.getBBox().width;};Transform.prototype.getHeight=function(){return this.wrapper.getBBox().height;};Transform.prototype.getCX=function(){var left=0;var right=this.origWidth;var center=right/2;var cx=left;switch(this.centerPoint){case Position.CENTER:cx=center;break;case Position.TOP_LEFT:cx=left;break;case Position.TOP_CENTER:cx=center;break;case Position.TOP_RIGHT:cx=right;break;case Position.MIDDLE_LEFT:cx=left;break;case Position.MIDDLE_RIGHT:cx=right;break;case Position.BOTTOM_LEFT:cx=left;break;case Position.BOTTOM_CENTER:cx=center;break;case Position.BOTTOM_RIGHT:cx=right;break;default:break;}
return cx;};Transform.prototype.getCY=function(){var top=0;var bottom=this.origHeight;var middle=bottom/2;var cy=top;switch(this.centerPoint){case Position.CENTER:cy=middle;break;case Position.TOP_LEFT:cy=top;break;case Position.TOP_CENTER:cy=top;break;case Position.TOP_RIGHT:cy=top;break;case Position.MIDDLE_LEFT:cy=middle;break;case Position.MIDDLE_RIGHT:cy=middle;break;case Position.BOTTOM_LEFT:cy=bottom;break;case Position.BOTTOM_CENTER:cy=bottom;break;case Position.BOTTOM_RIGHT:cy=bottom;break;default:break;}
return cy;};Transform.prototype.setX=function(x){this.setTransform({"x":x});this._x=x;};Transform.prototype.getX=function(){return this._x;};Transform.prototype.setY=function(y){this.setTransform({"y":y});this._y=y;};Transform.prototype.getY=function(){return this._y;};Transform.prototype.setScaleX=function(scaleX){this.setTransform({"scaleX":scaleX});};Transform.prototype.getScaleX=function(){return this._transform.scaleX;};Transform.prototype.setScaleY=function(scaleY){this.setTransform({"scaleY":scaleY});};Transform.prototype.getScaleY=function(){return this._transform.scaleY;};Transform.prototype.setRotate=function(rotate){this.setTransform({"rotate":rotate});};Transform.prototype.getRotate=function(){return this._transform.rotate;};if(typeof SVGUtil=="undefined"){global.SVGUtil={};}
global.SVGUtil.Transform=Transform;})(this);if(!SVGUtil.Transform){throw new Error("require: SVGTransformUtil");}
(function(global){function defineSetterGetter(obj,name,setter,getter){if(!Object.prototype.__defineSetter__&&Object.defineProperty({},"x",{get:function(){return true}}).x){Object.defineProperty(obj,name,{set:setter,get:getter});}else if(Object.prototype.__defineSetter__){obj.__defineSetter__(name,setter);obj.__defineGetter__(name,getter);}};var SVGSprite={};SVGSprite.tmpParent=document.createElementNS("http://www.w3.org/2000/svg","svg");SVGSprite.tmpParent.setAttribute("width",0);SVGSprite.tmpParent.setAttribute("height",0);SVGSprite.tmpParent.id="SVGSpriteTmpParent";SVGSprite.EventDispatcher=function(svgElement){this.svgElement=svgElement;}
SVGSprite.EventDispatcher.prototype.addEventListener=function(type,listener,useCapture){useCapture=(useCapture)?true:false;this._originalElement.addEventListener(type,listener,useCapture);}
SVGSprite.EventDispatcher.prototype.removeEventListener=function(type,listener,useCapture){useCapture=(useCapture)?true:false;this._originalElement.removeEventListener(type,listener,useCapture);}
SVGSprite.DisplayObject=function(svgElement){this.constructor(svgElement);}
SVGSprite.DisplayObject.prototype=new SVGSprite.EventDispatcher();defineSetterGetter(SVGSprite.DisplayObject.prototype,"svgElement",function(svgElement){if(typeof this._svgElement==="undefined"&&svgElement){var _svgElement=svgElement;if(typeof svgElement==="string"){var __svgElement=document.getElementById(svgElement);if(__svgElement){_svgElement=__svgElement;}else{var _SVGs=document.getElementsByTagName('object');for(var i=0;i<_SVGs.length;i++){if(_SVGs[i].type==="image/svg+xml"){_svgElement=_SVGs[i].contentDocument.getElementById(svgElement);}}}}
if(!_svgElement||_svgElement.namespaceURI!=="http://www.w3.org/2000/svg"){throw new Error("引数が SVG Element ではありません。");}
this.__prefix=(typeof _svgElement.prefix==="string")?_svgElement.prefix+":":"";if(_svgElement.parentNode==null){document.body.appendChild(SVGSprite.tmpParent);SVGSprite.tmpParent.appendChild(_svgElement);}
this._svgTransformUtil=new SVGUtil.Transform(_svgElement);this._originalElement=this._svgTransformUtil.sourceSVGElement;this._svgElement=document.createElementNS("http://www.w3.org/2000/svg",this.__prefix+"g");this._svgElement.setAttribute("class","SVGSprite");this._oapcityElement=document.createElementNS("http://www.w3.org/2000/svg",this.__prefix+"g");this._oapcityElement.setAttribute("class","SVGSpriteOpacityWrapper");this._svgTransformUtil.sourceSVGElement.parentNode.replaceChild(this._oapcityElement,this._svgTransformUtil.sourceSVGElement);this._oapcityElement.appendChild(this._svgTransformUtil.sourceSVGElement);this._svgTransformUtil.svgElement.parentNode.replaceChild(this._svgElement,this._svgTransformUtil.svgElement);this._svgElement.appendChild(this._svgTransformUtil.svgElement);this.sourceSVGElement=_svgElement;this.buttonMode=false;}},function(){return this._svgElement;});defineSetterGetter(SVGSprite.DisplayObject.prototype,"_prefix",function(){throw new Error("参照専用です。");},function(){return this.__prefix;});SVGSprite.DisplayObject.prototype._getViewPortScaleX=function(){var viewBoxWidth=this._svgElement.nearestViewportElement.viewBox.baseVal.width;var viewportWidth=this._svgElement.nearestViewportElement.width.baseVal.value;return(viewBoxWidth==0)?1:viewportWidth/viewBoxWidth;}
defineSetterGetter(SVGSprite.DisplayObject.prototype,"_viewPortScaleX",function(){throw new Error("参照専用です。");},function(){return this._getViewPortScaleX();});SVGSprite.DisplayObject.prototype._getViewPortScaleY=function(){var viewBoxHeight=this._svgElement.nearestViewportElement.viewBox.baseVal.height;var viewportHeight=this._svgElement.nearestViewportElement.height.baseVal.value;return(viewBoxHeight==0)?1:viewportHeight/viewBoxHeight;}
defineSetterGetter(SVGSprite.DisplayObject.prototype,"_viewPortScaleY",function(){throw new Error("参照専用です。");},function(){return this._getViewPortScaleY();});defineSetterGetter(SVGSprite.DisplayObject.prototype,"x",function(x){this._svgTransformUtil.setX(x);},function(){return this._svgTransformUtil.getX();});defineSetterGetter(SVGSprite.DisplayObject.prototype,"y",function(y){this._svgTransformUtil.setY(y);},function(){return this._svgTransformUtil.getY();});defineSetterGetter(SVGSprite.DisplayObject.prototype,"width",function(width){this.scaleX=width/this._svgTransformUtil.origWidth;},function(){return this._svgTransformUtil.getWidth();});defineSetterGetter(SVGSprite.DisplayObject.prototype,"height",function(height){this.scaleY=height/this._svgTransformUtil.origHeight;},function(){return this._svgTransformUtil.getHeight();});defineSetterGetter(SVGSprite.DisplayObject.prototype,"scaleX",function(scaleX){this._svgTransformUtil.setScaleX(scaleX);},function(){return this._svgTransformUtil.getScaleX();});defineSetterGetter(SVGSprite.DisplayObject.prototype,"scaleY",function(scaleY){this._svgTransformUtil.setScaleY(scaleY);},function(){return this._svgTransformUtil.getScaleY();});defineSetterGetter(SVGSprite.DisplayObject.prototype,"rotation",function(rotation){this._svgTransformUtil.setRotate(rotation);},function(){return this._svgTransformUtil.getRotate();});SVGSprite.DisplayObject.prototype._getAlpha=function(){var _alpha=this._oapcityElement.getAttribute('opacity');return Number((typeof _alpha==='string')?_alpha:1);}
defineSetterGetter(SVGSprite.DisplayObject.prototype,"alpha",function(alpha){var _alpha=Number(alpha);if(0<=_alpha&&_alpha<=1){this._oapcityElement.setAttribute('opacity',_alpha);}},function(){return this._getAlpha();});defineSetterGetter(SVGSprite.DisplayObject.prototype,"buttonMode",function(buttonMode){this._buttonMode=Boolean(buttonMode);if(this._buttonMode){this.svgElement.setAttributeNS(null,"style","cursor: move");}else{this.svgElement.setAttributeNS(null,"style","cursor: normal");}},function(){return this._buttonMode;});SVGSprite.DisplayObjectContainer=function(svgElement){this.constructor(svgElement);};SVGSprite.DisplayObjectContainer.prototype=new SVGSprite.DisplayObject();SVGSprite.DisplayObjectContainer.prototype.addChild=function(child){throw new Error("未実装です。");};SVGSprite.DisplayObjectContainer.prototype.appendTo=function(content){content.appendChild(this.svgElement);};SVGSprite.Sprite=function(svgElement){this.constructor(svgElement);}
SVGSprite.Sprite.prototype=new SVGSprite.DisplayObjectContainer();SVGSprite.Sprite.prototype.startDrag=function(lockCenter,bounds){this.svgElement.ownerSVGElement.addEventListener("mousedown",function(e){e.preventDefault();},false);if(typeof bounds!="undefined"&&bounds!=null&&!isNaN(bounds.x)&&!isNaN(bounds.y)&&!isNaN(bounds.width)&&!isNaN(bounds.height)){this._bounds=bounds;this._bounds.left=this._bounds.x;this._bounds.right=this._bounds.x+this._bounds.width;this._bounds.top=this._bounds.y;this._bounds.bottom=this._bounds.y+this._bounds.height;}else{this._bounds=null;}
SVGSprite.Sprite.drag.startDrag(this);}
SVGSprite.Sprite.prototype.stopDrag=function(){SVGSprite.Sprite.drag.stopDrag();}
SVGSprite.Sprite.drag={target:null,origX:0,origY:0,origMouseX:null,origMouseY:null};SVGSprite.Sprite.drag.startDrag=function(target){this.target=target;this.origX=target.x;this.origY=target.y;SVGSprite.Sprite.drag.target.svgElement.ownerSVGElement.addEventListener("mousemove",SVGSprite.Sprite.drag._doDrag,true);}
SVGSprite.Sprite.drag._doDrag=function(event){var that=SVGSprite.Sprite.drag;if(that.origMouseX==null){that.origMouseX=event.clientX;that.origMouseY=event.clientY;}
var x=((event.clientX-that.origMouseX)/that.target._viewPortScaleX)+that.origX;var y=((event.clientY-that.origMouseY)/that.target._viewPortScaleY)+that.origY;if(that.target._bounds!=null){x=(x<that.target._bounds.left)?that.target._bounds.left:(x+that.target.width>that.target._bounds.right)?that.target._bounds.right-that.target.width:x;y=(y<that.target._bounds.top)?that.target._bounds.top:(y+that.target.height>that.target._bounds.bottom)?that.target._bounds.bottom-that.target.height:y;}
that.target.x=x;that.target.y=y;}
SVGSprite.Sprite.drag.stopDrag=function(){var that=SVGSprite.Sprite.drag;if(SVGSprite.Sprite.drag.target!=null){SVGSprite.Sprite.drag.target.svgElement.ownerSVGElement.removeEventListener("mousemove",SVGSprite.Sprite.drag._doDrag,true);}
that.target=null;that.origX=0;that.origY=0;that.origMouseX=null;that.origMouseY=null;}
global.SVGSprite=SVGSprite;})(this);